# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("7"))
        self.sevenbutton.setGeometry(QtCore.QRect(30, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setIconSize(QtCore.QSize(16, 16))
        self.sevenbutton.setObjectName("sevenbutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("8"))
        self.eightbutton.setGeometry(QtCore.QRect(120, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.eightbutton.setFont(font)
        self.eightbutton.setIconSize(QtCore.QSize(16, 16))
        self.eightbutton.setObjectName("eightbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("9"))
        self.ninebutton.setGeometry(QtCore.QRect(210, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ninebutton.setFont(font)
        self.ninebutton.setIconSize(QtCore.QSize(16, 16))
        self.ninebutton.setObjectName("ninebutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("4"))
        self.fourbutton.setGeometry(QtCore.QRect(30, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.fourbutton.setFont(font)
        self.fourbutton.setIconSize(QtCore.QSize(16, 16))
        self.fourbutton.setObjectName("fourbutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("6"))
        self.sixbutton.setGeometry(QtCore.QRect(210, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.sixbutton.setFont(font)
        self.sixbutton.setIconSize(QtCore.QSize(16, 16))
        self.sixbutton.setObjectName("sixbutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("5"))
        self.fivebutton.setGeometry(QtCore.QRect(120, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.fivebutton.setFont(font)
        self.fivebutton.setIconSize(QtCore.QSize(16, 16))
        self.fivebutton.setObjectName("fivebutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("1"))
        self.onebutton.setGeometry(QtCore.QRect(30, 330, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.onebutton.setFont(font)
        self.onebutton.setIconSize(QtCore.QSize(16, 16))
        self.onebutton.setObjectName("onebutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("3"))
        self.threebutton.setGeometry(QtCore.QRect(210, 330, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.threebutton.setFont(font)
        self.threebutton.setIconSize(QtCore.QSize(16, 16))
        self.threebutton.setObjectName("threebutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("2"))
        self.twobutton.setGeometry(QtCore.QRect(120, 330, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.twobutton.setFont(font)
        self.twobutton.setIconSize(QtCore.QSize(16, 16))
        self.twobutton.setObjectName("twobutton")
        self.dividebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.operate("/"))
        self.dividebutton.setGeometry(QtCore.QRect(300, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.dividebutton.setFont(font)
        self.dividebutton.setIconSize(QtCore.QSize(16, 16))
        self.dividebutton.setObjectName("dividebutton")
        self.multibutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.operate("*"))
        self.multibutton.setGeometry(QtCore.QRect(300, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.multibutton.setFont(font)
        self.multibutton.setIconSize(QtCore.QSize(16, 16))
        self.multibutton.setObjectName("multibutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.operate("-"))
        self.minusbutton.setGeometry(QtCore.QRect(300, 330, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.minusbutton.setFont(font)
        self.minusbutton.setIconSize(QtCore.QSize(16, 16))
        self.minusbutton.setObjectName("minusbutton")
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.result())
        self.equalbutton.setGeometry(QtCore.QRect(30, 410, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.equalbutton.setFont(font)
        self.equalbutton.setIconSize(QtCore.QSize(16, 16))
        self.equalbutton.setObjectName("equalbutton")
        self.zerobutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("0"))
        self.zerobutton.setGeometry(QtCore.QRect(120, 410, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.zerobutton.setFont(font)
        self.zerobutton.setIconSize(QtCore.QSize(16, 16))
        self.zerobutton.setObjectName("zerobutton")
        self.dotbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot())
        self.dotbutton.setGeometry(QtCore.QRect(210, 410, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.dotbutton.setFont(font)
        self.dotbutton.setIconSize(QtCore.QSize(16, 16))
        self.dotbutton.setObjectName("dotbutton")
        self.plusbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.operate("+"))
        self.plusbutton.setGeometry(QtCore.QRect(300, 410, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.plusbutton.setFont(font)
        self.plusbutton.setIconSize(QtCore.QSize(16, 16))
        self.plusbutton.setObjectName("plusbutton")
        self.cebutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("CE"))
        self.cebutton.setGeometry(QtCore.QRect(30, 490, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.cebutton.setFont(font)
        self.cebutton.setIconSize(QtCore.QSize(16, 16))
        self.cebutton.setObjectName("cebutton")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press("C"))
        self.cbutton.setGeometry(QtCore.QRect(200, 490, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.cbutton.setFont(font)
        self.cbutton.setIconSize(QtCore.QSize(16, 16))
        self.cbutton.setObjectName("cbutton")
        self.textbox = QtWidgets.QLabel(self.centralwidget)
        self.textbox.setGeometry(QtCore.QRect(30, 20, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.textbox.setFont(font)
        self.textbox.setFrameShape(QtWidgets.QFrame.Box)
        self.textbox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.textbox.setObjectName("textbox")
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.operationlabel = QtWidgets.QLabel(self.centralwidget)
        self.operationlabel.setEnabled(True)
        self.operationlabel.setGeometry(QtCore.QRect(30, 20, 30, 30))
        self.operationlabel.setFont(font)
        self.operationlabel.setText("")
        self.operationlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.operationlabel.setObjectName("operationlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
##Calculator Processing##
    global backresult,operation,dotstatus
    backresult = ""
    operation = ["+","-","*","/"]
    dotstatus = "+"
    def result(self):
        global backresult,operation,dotstatus
        if backresult[-1] in operation:
            backresult = backresult[:-1]
        elif backresult != "":
            if backresult[-1]!="0" and backresult[-2]!="/":
                backresult = str(round(eval(backresult),9))
                self.textbox.setText(backresult)
            else:
                self.textbox.setText("Undefined")
        else:
            self.textbox.setText("0")
        self.operationlabel.setText("")
        dotstatus = "-"
    def dot(self):
        global backresult,operation,dotstatus
        if dotstatus == "+":
            if backresult[-1] in operation:
                self.textbox.setText("0")
                backresult += "0"
            self.textbox.setText(f"{self.textbox.text()}.")
            backresult += "."
            dotstatus = "-"
    def operate(self,x):
        global backresult,operation,dotstatus
        if x=="/":
            self.operationlabel.setText("÷")
        elif x=="*":
            self.operationlabel.setText("×")
        elif x=="-":
            self.operationlabel.setText("−")
        else:
            self.operationlabel.setText("+")
        if backresult[-1] in operation:
            backresult = backresult[:-1]
        if "+" in backresult or "-" in backresult or "*" in backresult or "/" in backresult:
            if backresult[-1] not in operation:
                backresult=str(round(eval(backresult),9))
                self.textbox.setText(backresult)
        backresult += x
        dotstatus = "+"
    def press(self,x):
        global backresult
        if x == "C":
            self.textbox.setText("0")
            self.operationlabel.setText("")
            backresult = ""
        elif x == "CE":
            if "+" in backresult or "-" in backresult or "*" in backresult or "/" in backresult:
                test = backresult[::-1]
                for check in test:
                    if check in operation:
                        backresult = test[::-1]
                        self.textbox.setText("0")
                        break
                    test = test[1:]
            else:
                self.textbox.setText("0")
                self.operationlabel.setText("")
                backresult=""
        elif backresult != "":
            if backresult[-1] in operation:
                self.textbox.setText(x)
                backresult += x
            else:
                if self.textbox.text() == "0":
                    self.textbox.setText("")
                if backresult[-1]=="0" and backresult[-2] in operation:
                    backresult = backresult[:-1]
                self.textbox.setText(f"{self.textbox.text()}{x}")
                backresult += x
        elif backresult == "":
            if x != "0":
                self.textbox.setText("")
                self.textbox.setText(x)
                backresult += x
##Calculator Processing##

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator by Parintorn Thammasitboon"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.dividebutton.setText(_translate("MainWindow", "÷"))
        self.multibutton.setText(_translate("MainWindow", "×"))
        self.minusbutton.setText(_translate("MainWindow", "−"))
        self.equalbutton.setText(_translate("MainWindow", "="))
        self.zerobutton.setText(_translate("MainWindow", "0"))
        self.dotbutton.setText(_translate("MainWindow", "."))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.cebutton.setText(_translate("MainWindow", "CE"))
        self.cbutton.setText(_translate("MainWindow", "C"))
        self.textbox.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
